Generates the plots and tables for paper "RDMDL ..."

In [2]:
from bicausal.metrics.evaluators import evaluate_lisbon, evaluate_tuebingen, construct_table

In [4]:
evaluate_tuebingen(metrics=["LxCIM","accuracy","AUROC","AUDRC"])
construct_table(datasets=["Tuebingen"], metrics=["LxCIM","accuracy","AUROC","AUDRC"], include_variations=True, table_title="RDMDL Table 1")

✅ Evaluation complete. Results written to results/results.csv

================================================================================
RESULT TABLE
================================================================================
| Method   | Parameters                                       | Dataset   |   LxCIM (%) |   Accuracy (%) |   AUROC (%) |   AUDRC (%) |
|----------|--------------------------------------------------|-----------|-------------|----------------|-------------|-------------|
| ANM      |                                                  | Tübingen  |        61.7 |           60.4 |        61.9 |        62.9 |
| bQCD     |                                                  | Tübingen  |        71.1 |           69.6 |        71.1 |        70.1 |
| CAM      |                                                  | Tübingen  |        45.7 |           52.3 |        46.6 |        43.1 |
| CDCI     |                                                  | Tübingen  |        59.4 |           61.5 |        60.7 |        55   |
| CDS      |                                                  | Tübingen  |        60.2 |           60.5 |        59   |        57.8 |
| CGNN     | {"nruns": 3,"test_epochs": 2,"train_epochs": 10} | Tübingen  |        62.8 |           61.5 |        61.6 |        69.6 |
| FOM      |                                                  | Tübingen  |        46.1 |           45.5 |        45.1 |        40.9 |
| HECI     |                                                  | Tübingen  |        74.1 |           70.5 |        75.3 |        79.2 |
| IGCI     |                                                  | Tübingen  |        70   |           60.9 |        69.8 |        73.3 |
| LCube    |                                                  | Tübingen  |        62.4 |           58.9 |        58   |        70.1 |
| LOCI     |                                                  | Tübingen  |        59.4 |           61.5 |        57.4 |        49.5 |
| NNCL     |                                                  | Tübingen  |        63.6 |           55.2 |        65.3 |        63.4 |
| rdmdl    |                                                  | Tübingen  |        74.6 |           64.8 |        74   |        79.2 |
| rdmdl    | {"delta": "res"}                                 | Tübingen  |        75.2 |           70.2 |        74.6 |        78.7 |
| RECI     |                                                  | Tübingen  |        76.1 |           70.5 |        76.4 |        75.7 |
| ROCHE    |                                                  | Tübingen  |        56.7 |           53   |        56.7 |        53.7 |
| Slope    |                                                  | Tübingen  |        81.1 |           73.3 |        80.5 |        86.4 |
| Sloppy   |                                                  | Tübingen  |        79.4 |           72.6 |        79.3 |        85.3 |
================================================================================

Table saved to: table\RDMDL Table 1.tex

,Method,Parameters,Dataset,LxCIM (%),Accuracy (%),AUROC (%),AUDRC (%)
0,ANM,,Tübingen,61.7,60.4,61.9,62.9
15,bQCD,,Tübingen,71.1,69.6,71.1,70.1
1,CAM,,Tübingen,45.7,52.3,46.6,43.1
2,CDCI,,Tübingen,59.4,61.5,60.7,55.0
3,CDS,,Tübingen,60.2,60.5,59.0,57.8
4,CGNN,"{""nruns"": 3,""test_epochs"": 2,""train_epochs"": 10}",Tübingen,62.8,61.5,61.6,69.6
5,FOM,,Tübingen,46.1,45.5,45.1,40.9
6,HECI,,Tübingen,74.1,70.5,75.3,79.2
7,IGCI,,Tübingen,70.0,60.9,69.8,73.3
8,LCube,,Tübingen,62.4,58.9,58.0,70.1
9,LOCI,,Tübingen,59.4,61.5,57.4,49.5
10,NNCL,,Tübingen,63.6,55.2,65.3,63.4
16,rdmdl,,Tübingen,74.6,64.8,74.0,79.2
17,rdmdl,"{""delta"": ""res""}",Tübingen,75.2,70.2,74.6,78.7
11,RECI,,Tübingen,76.1,70.5,76.4,75.7
12,ROCHE,,Tübingen,56.7,53.0,56.7,53.7
13,Slope,,Tübingen,81.1,73.3,80.5,86.4
14,Sloppy,,Tübingen,79.4,72.6,79.3,85.3

In [7]:
evaluate_lisbon(metrics=["LxCIM","accuracy","AUROC","AUDRC"])
construct_table(datasets=["Lisbon"], metrics=["LxCIM","accuracy","AUROC","AUDRC"], include_variations=True, table_title="RDMDL Table 2")

✅ Evaluation complete. Results written to results/results.csv
✅ Evaluation complete. Results written to results/results.csv
✅ Evaluation complete. Results written to results/results.csv
✅ Evaluation complete. Results written to results/results.csv
✅ Evaluation complete. Results written to results/results.csv
✅ Evaluation complete. Results written to results/results.csv

================================================================================
RESULT TABLE
================================================================================
| Method   | Parameters                                       | Dataset   |   LxCIM (%) |   Accuracy (%) |   AUROC (%) |   AUDRC (%) |
|----------|--------------------------------------------------|-----------|-------------|----------------|-------------|-------------|
| ANM      |                                                  | Lisbon    |        56.9 |           57.6 |        56.8 |        58.3 |
| bQCD     |                                                  | Lisbon    |        60.1 |           59.4 |        59.9 |        59.7 |
| CAM      |                                                  | Lisbon    |        47.1 |           49.7 |        47.2 |        44.5 |
| CDCI     |                                                  | Lisbon    |        62.4 |           57.5 |        62.3 |        65.3 |
| CDS      |                                                  | Lisbon    |        47.7 |           50.3 |        47.7 |        43.7 |
| CGNN     | {"nruns": 3,"test_epochs": 2,"train_epochs": 10} | Lisbon    |        50.7 |           51.4 |        50.7 |        52.1 |
| FOM      |                                                  | Lisbon    |        38.9 |           42.4 |        38.9 |        37.2 |
| HECI     |                                                  | Lisbon    |        56.3 |           58.3 |        56.5 |        54.2 |
| IGCI     |                                                  | Lisbon    |        66   |           63.2 |        65.8 |        64.1 |
| LCube    |                                                  | Lisbon    |        46.4 |           40   |        46.3 |        51.5 |
| LOCI     |                                                  | Lisbon    |        56.8 |           57   |        56.8 |        56.3 |
| NNCL     |                                                  | Lisbon    |        56.9 |           56.4 |        56.9 |        57.9 |
| rdmdl    |                                                  | Lisbon    |        68.7 |           65.1 |        68.6 |        68   |
| rdmdl    | {"delta": "res"}                                 | Lisbon    |        68.9 |           65.8 |        68.8 |        67.1 |
| RECI     |                                                  | Lisbon    |        56.3 |           55.5 |        56.2 |        56.4 |
| ROCHE    |                                                  | Lisbon    |        39.6 |           42.9 |        39.5 |        35.9 |
| Slope    |                                                  | Lisbon    |        56.6 |           54.1 |        56.7 |        55.1 |
| Sloppy   |                                                  | Lisbon    |        56.5 |           56.8 |        56.4 |        54.5 |
================================================================================

Table saved to: table\RDMDL Table 2.tex

,Method,Parameters,Dataset,LxCIM (%),Accuracy (%),AUROC (%),AUDRC (%)
0,ANM,,Lisbon,56.9,57.6,56.8,58.3
15,bQCD,,Lisbon,60.1,59.4,59.9,59.7
1,CAM,,Lisbon,47.1,49.7,47.2,44.5
2,CDCI,,Lisbon,62.4,57.5,62.3,65.3
3,CDS,,Lisbon,47.7,50.3,47.7,43.7
4,CGNN,"{""nruns"": 3,""test_epochs"": 2,""train_epochs"": 10}",Lisbon,50.7,51.4,50.7,52.1
5,FOM,,Lisbon,38.9,42.4,38.9,37.2
6,HECI,,Lisbon,56.3,58.3,56.5,54.2
7,IGCI,,Lisbon,66.0,63.2,65.8,64.1
8,LCube,,Lisbon,46.4,40.0,46.3,51.5
9,LOCI,,Lisbon,56.8,57.0,56.8,56.3
10,NNCL,,Lisbon,56.9,56.4,56.9,57.9
16,rdmdl,,Lisbon,68.7,65.1,68.6,68.0
17,rdmdl,"{""delta"": ""res""}",Lisbon,68.9,65.8,68.8,67.1
11,RECI,,Lisbon,56.3,55.5,56.2,56.4
12,ROCHE,,Lisbon,39.6,42.9,39.5,35.9
13,Slope,,Lisbon,56.6,54.1,56.7,55.1
14,Sloppy,,Lisbon,56.5,56.8,56.4,54.5